#!/bin/bash

./uArmMC -t km_test > /tmp/out
awk -F'\t' '/^km_test.0/ { printf("# %.2f %.2f %.2f\nG1 W1 F20 L%d R%d O%d\n", $5, $6, $7, $2, $3, $4) }' /tmp/out > /tmp/g
awk -F'\t' '/^km_test.0/ { print $5, $6, $7 }' /tmp/out > /tmp/a
gnuplot << EOF
set terminal png
set output '/tmp/a.png'

set xlabel 'X'
set ylabel 'Y'
set zlabel 'Z'

set title 'Accessible servo positions for the Lite Arm i2'

set palette model RGB defined ( -100 'magenta', 500 'cyan')
splot '/tmp/a' u 1:2:3:3 with d palette
EOF
